# Generated by Django 4.1.7 on 2023-03-28 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sneakers_images', verbose_name='Изображение')),
                ('sneakers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nike')),
            ],
        ),
    ]
