# Generated by Django 4.1.7 on 2023-03-28 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nike',
            new_name='New_Balance',
        ),
    ]
