# Generated by Django 4.1.7 on 2023-03-28 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_nike_new_balance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New_Balance',
            new_name='NewBalance',
        ),
    ]
