# Generated by Django 4.1.7 on 2023-03-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_new_balance_newbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newbalance',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
